### PR TITLE
feat: Fonts Added

### PR DESCRIPTION
**Pull request by Rushi67**

### CODE REVIEW

**Comment by Rushi67** [comment]
don't merge 
Extra light font is missing

**Comment by psantosh16** [comment]
fonts/Gilroy/Gilroy-ExtraLight.ttf is present. @Rushi67 check recent commit

**Comment by psantosh16** [comment]
Screenshot 2024-07-28 at 3 09 51 PM

**Comment by Rushi67** [comment]
It was actually Gilroy Heavy .. to avoid error it was rename as Extralight

**Review by psantosh16 — APPROVED** [review]

**Pull request merged**
